server.port=${SERVER_PORT}
# BBDD configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Flyway
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true
spring.flyway.locations=classpath:db/migration/prod
spring.flyway.schemas=public
logging.level.org.flywaydb=INFO
# Secret
jwt.secret=${JWT_SECRET}