server.port=8085
# BBDD configuration
spring.datasource.url=jdbc:h2:mem:auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.h2.Driver
# Flyway
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true
spring.flyway.locations=classpath:db/migration/dev
spring.flyway.schemas=public
logging.level.org.flywaydb=INFO