spring.application.name=auth-service
# I just want jpa to act as an entity to only access the db, not to generate the table
spring.jpa.hibernate.ddl-auto=none

grpc.server.port=9091

# JWT TTLs (HU-USR-02)
jwt.access-token.ttl-minutes=60
jwt.refresh-token.ttl-days=7

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
