spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

grpc.client.auth-service.address=static://auth-service:9091
grpc.client.auth-service.negotiation-type=plaintext
grpc.client.terrain-service.address=static://terrain-service:9093
grpc.client.terrain-service.negotiation-type=plaintext
