spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# change db credentials
# gRPC Client Configuration
grpc.client.auth-service.address=static://auth-service:9091
grpc.client.auth-service.negotiation-type=plaintext