spring.datasource.url=jdbc:postgresql://localhost:5436/task_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

grpc.client.auth-service.address=static://localhost:9091
grpc.client.auth-service.negotiation-type=plaintext
grpc.client.terrain-service.address=static://localhost:9093
grpc.client.terrain-service.negotiation-type=plaintext

terrain-service.base-url=http://localhost:8080
