spring.datasource.url=jdbc:postgresql://localhost:5434/season_db
spring.datasource.username=postgres
spring.datasource.password=postgres
# gRPC Client Configuration
grpc.client.terrain-service.address=static://localhost:9093
grpc.client.terrain-service.negotiation-type=plaintext
grpc.client.crop-service.address=static://localhost:9094
grpc.client.crop-service.negotiation-type=plaintext